# --- Etapa base ---
FROM node:18-alpine

# 1️⃣ Argumentos del build (usados opcionalmente por docker-compose build)
ARG PORT
ARG POSTGRES_PASSWORD
ARG POSTGRES_USER
ARG JWT_SECRET
ARG DB_NAME
ARG NATS_SERVERS
ARG DATABASE_URL
ARG HOST
ARG GOOGLE_CLIENT_ID

# --- Keycloak ARGs ---
ARG KEYCLOAK_DOMAIN
ARG KEYCLOAK_REALM
ARG KEYCLOAK_CLIENT_ID
ARG KEYCLOAK_CLIENT_SECRET
ARG KEYCLOAK_LOGIN_URL
ARG KEYCLOAK_ADMIN_BASE_URL
ARG KEYCLOAK_ADMIN_CLIENT_ID
ARG KEYCLOAK_ADMIN_CLIENT_SECRET
ARG KEYCLOAK_ADMIN_LINK_LIFESPAN
ARG KEYCLOAK_ADMIN_REDIRECT_URI
ARG KEYCLOAK_CLIENT_LOGIN_CLIENT_ID
ARG KEYCLOAK_CLIENT_LOGIN_CLIENT_SECRET
ARG DATABASE_HOST
ARG DATABASE_PORT

# 2️⃣ Variables de entorno (sin espacios en los "=")
ENV PORT=$PORT \
    POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
    POSTGRES_USER=$POSTGRES_USER \
    JWT_SECRET=$JWT_SECRET \
    DB_NAME=$DB_NAME \
    NATS_SERVERS=$NATS_SERVERS \
    DATABASE_URL=$DATABASE_URL \
    HOST=$HOST \
    GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID \
    KEYCLOAK_DOMAIN=$KEYCLOAK_DOMAIN \
    KEYCLOAK_REALM=$KEYCLOAK_REALM \
    KEYCLOAK_CLIENT_ID=$KEYCLOAK_CLIENT_ID \
    KEYCLOAK_CLIENT_SECRET=$KEYCLOAK_CLIENT_SECRET \
    KEYCLOAK_LOGIN_URL=$KEYCLOAK_LOGIN_URL \
    KEYCLOAK_ADMIN_BASE_URL=$KEYCLOAK_ADMIN_BASE_URL \
    KEYCLOAK_ADMIN_CLIENT_ID=$KEYCLOAK_ADMIN_CLIENT_ID \
    KEYCLOAK_ADMIN_CLIENT_SECRET=$KEYCLOAK_ADMIN_CLIENT_SECRET \
    KEYCLOAK_ADMIN_LINK_LIFESPAN=$KEYCLOAK_ADMIN_LINK_LIFESPAN \
    KEYCLOAK_ADMIN_REDIRECT_URI=$KEYCLOAK_ADMIN_REDIRECT_URI \
    KEYCLOAK_CLIENT_LOGIN_CLIENT_ID=$KEYCLOAK_CLIENT_LOGIN_CLIENT_ID \
    KEYCLOAK_CLIENT_LOGIN_CLIENT_SECRET=$KEYCLOAK_CLIENT_LOGIN_CLIENT_SECRET \
    DATABASE_HOST=$DATABASE_HOST \
    DATABASE_PORT=$DATABASE_PORT

# 3️⃣ Dependencias del sistema
RUN apk add --no-cache python3 make g++

# 4️⃣ Directorio de trabajo
WORKDIR /usr/src/app

# 5️⃣ Copiar dependencias e instalarlas
COPY package*.json ./
RUN npm install

# 6️⃣ Instalar herramientas globales (NestJS CLI + TypeScript)
RUN npm install -g ts-node typescript @nestjs/cli

# 7️⃣ Copiar el resto del código fuente
COPY . .

# 8️⃣ Exponer el puerto del microservicio
EXPOSE ${PORT}

# 9️⃣ Comando de inicio
# Para desarrollo (hot reload):
CMD ["npm", "run", "start:dev"]

# Si fuera producción (sin hot reload):
# CMD ["npm", "run", "start:prod"]
